version: '3'
services:
  benchmark:
    container_name: benchmark
    build: .
    ports:
      - 5432:5432
      - 8888:8888
    volumes:
      - ./db/data:/var/lib/postgresql/data
      - ./data:/app/data
      - ./experiments:/app/experiments
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - DATABASE_URL=postgres://postgres:postgres@localhost:5432/postgres
      - NEON_DATABASE_URL=postgres://postgres:postgres@localhost:5432/neon
      - PGVECTOR_DATABASE_URL=postgres://postgres:postgres@localhost:5432/pgvector
      - LANTERN_DATABASE_URL=postgres://postgres:postgres@localhost:5432/lantern
