version: '3'
services:
  benchmark:
    container_name: benchmark
    build: .
    ports:
      - 5432:5432
      - 8888:8888
    volumes:
      - ./db/data:/var/lib/postgresql/data
      - ./db/scripts:/app/db/scripts
      - ./data:/app/data
      - ./experiments:/app/experiments
      - ./requirements.txt:/app/requirements.txt
    environment:
      - DATABASE_URL=postgres://postgres:postgres@localhost:5432/postgres
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_PORT=5432
